# On Darkness as a Veil for Wickedness

The day has already begun to lessen.
It has shrunk considerably, but yet will still allow a goodly space of time if one rises, so to speak, with the day itself.
We are more industrious, and we are better men if we anticipate the day and welcome the dawn; but we are base churls if we lie dozing when the sun is high in the heavens, or if we wake up only when noon arrives; and even then to many it seems not yet dawn.

Some have reversed the functions of light and darkness; they open eyes sodden with yesterday's debauch only at the approach of night.
It is just like the condition of those peoples whom, according to Vergil, Nature has hidden away and placed in an abode directly opposite to our own:

> When in our face the Dawn with panting steeds  
Breathes down, for them the ruddy evening kindles  
Her late-lit fires.[^122-1]

It is not the country of these men, so much as it is their life, that is "directly opposite" to our own.

There may be Antipodes dwelling in this same city of ours who, in Cato's words,[^122-2] "have never seen the sun rise or set."
Do you think that these men know *how* to live, if they do not know *when* to live?
Do these men fear death, if they have buried themselves alive?
They are as weird as the birds of night.[^122-3]
Although they pass their hours of darkness amid wine and perfumes, although they spend the whole extent of their unnatural waking hours in eating dinners -- and those too cooked separately to make up many courses -- they are not really banqueting; they are conducting their own funeral services.
And the dead at least have their banquets by daylight.[^122-4]

But indeed to one who is active no day is long.
So let us lengthen our lives; for the duty and the proof of life consist in action.
Cut short the night; use some of it for the day's business.

Birds that are being prepared for the banquet, that they may be easily fattened through lack of exercise, are kept in darkness; and similarly, if men vegetate without physical activity, their idle bodies are overwhelmed with flesh, and in their self-satisfied retirement the fat of indolence grows upon them.
Moreover, the bodies of those who have sworn allegiance to the hours of darkness have a loathsome appearance.
Their complexions are more alarming than those of anaemic invalids; they are lackadaisical and flabby with dropsy; though still alive, they are already carrion.
But this, to my thinking, would be among the least of their evils.
How much more darkness there is in their souls!
Such a man is internally dazed; his vision is darkened; he envies the blind.
And what man ever had eyes for the purpose of seeing in the dark?

You ask me how this depravity comes upon the soul -- this habit of reversing the daylight and giving over one's whole existence to the night?
All vices rebel against Nature; they all abandon the appointed order.
It is the motto of luxury to enjoy what is unusual, and not only to depart from that which is right, but to leave it as far behind as possible, and finally even take a stand in opposition thereto.

Do you not believe that men live contrary to Nature who drink fasting,[^122-5] who take wine into empty veins, and pass to their food in a state of intoxication?
And yet this is one of youth's popular vices -- to perfect their strength in order to drink on the very threshold of the bath, amid the unclad bathers; nay even to soak in wine and then immediately to rub off the sweat which they have promoted by many a hot glass of liquor!
To them, a glass after lunch or one after dinner is *bourgeois*; it is what the country squires do, who are not connoisseurs in pleasure.
This unmixed wine delights them just because there is no food to float in it, because it readily makes its way into their muscles; this boozing pleases them just because the stomach is empty.

Do you not believe that men live contrary to Nature who exchange the fashion of their attire with women?[^122-6]
Do not men live contrary to Nature who endeavour to look fresh and boyish at an age unsuitable for such an attempt?
What could be more cruel or more wretched?
Cannot time and man's estate ever carry such a person beyond an artificial boyhood?[^122-7]

Do not men live contrary to Nature who crave roses in winter, or seek to raise a spring flower like the lily by means of hot-water heaters and artificial changes of temperature?
Do not men live contrary to Nature who grow fruit-trees on the top of a wall?
Or raise waving forests upon the roofs and battlements of their houses -- the roots starting at a point to which it would be outlandish for the tree-tops to reach?
Do not men live contrary to Nature who lay the foundations of bathrooms in the sea and do not imagine that they can enjoy their swim unless the heated pool is lashed as with the waves of a storm?

When men have begun to desire all things in opposition to the ways of Nature, they end by entirely abandoning the ways of Nature.
They cry: "It is daytime: let us go to sleep!
It is the time when men rest: now for exercise, now for our drive, now for our lunch!
Lo, the dawn approaches: it is dinner-time!
We should not do as mankind do.
It is low and mean to live in the usual and conventional way.
Let us abandon the ordinary sort of day.
Let us have a morning that is a special feature of ours, peculiar to ourselves!"

Such men are, in my opinion, as good as dead.
Are they not all but present at a funeral -- and before their time too -- when they live amid torches and tapers?[^122-8]
I remember that this sort of life was very fashionable at one time: among such men as Acilius Buta, a person of praetorian rank, who ran through a tremendous estate and on confessing his bankruptcy to Tiberius, received the answer: "You have waked up too late!"

Julius Montanus was once reading a poem aloud; he was a middling good poet, noted for his friendship with Tiberius, as well as his fall from favour.
He always used to fill his poems with a generous sprinkling of sunrises and sunsets.
Hence, when a certain person was complaining that Montanus had read all day long, and declared that no man should attend any of his readings, Natta Pinarius[^122-9] remarked: "I couldn't make a fairer bargain than this: I am ready to listen to him from sunrise to sunset!"

Montanus was reading, and had reached the words:[^122-10]

> 'Gins the bright morning to spread forth his flames clear-burning; the red dawn  
Scatters its light; and the sad-eyed swallow[^122-11] returns to her nestlings,  
Bringing the chatterers' food, and with sweet bill sharing and serving.  

Then Varus, a Roman knight, the hanger-on of Marcus Vinicius,[^122-12] and a sponger at elegant dinners which he earned by his degenerate wit, shouted: "Bed-time for Buta!"

And later, when Montanus declaimed:

> Lo, now the shepherds have folded their flocks, and the slow-moving darkness  
'Gins to spread silence o'er lands that are drowsily lulled into slumber,

<p style="text-indent: 0">this same Varus remarked: "What?
Night already?
I'll go and pay my morning call on Buta!"
You see, nothing was more notorious than Buta's upside-down manner of life.
But this life, as I said, was fashionable at one time.</p>

And the reason why some men live thus is not because they think that night in itself offers any greater attractions, but because that which is normal gives them no particular pleasure; light being a bitter enemy of the evil conscience, and, when one craves or scorns all things in proportion as they have cost one much or little, illumination for which one does not pay is an object of contempt.
Moreover, the luxurious person wishes to be an object of gossip his whole life; if people are silent about him, he thinks that he is wasting his time.
Hence he is uncomfortable whenever any of his actions escape notoriety.

Many men eat up their property, and many men keep mistresses.
If you would win a reputation among such persons, you must make your programme not only one of luxury but one of notoriety; for in such a busy community wickedness does not discover the ordinary sort of scandal.

I heard Pedo Albinovanus, that most attractive story-teller, speaking of his residence above the town-house of Sextus Papinius.
Papinius belonged to the tribe of those who shun the light.
"About nine o'clock at night I hear the sound of whips.
I ask what is going on, and they tell me that Papinius is going over his accounts.[^122-13]
About twelve there is a strenuous shouting; I ask what the matter is, and they say he is exercising his voice.
About two A.M. I ask the significance of the sound of wheels; they tell me that he is off for a drive.

And at dawn there is a tremendous flurry-calling of slaves and butlers, and pandemonium among the cooks.
I ask the meaning of this also, and they tell me that he has called for his cordial and his appetizer, after leaving the bath.
His dinner," said Pedo, "never went beyond the day,[^122-14] for he lived very sparingly; he was lavish with nothing but the night.
Accordingly, if you believe those who call him tight-fisted and mean, you will call him also a 'slave of the lamp.'"[^122-15]

You should not be surprised at finding so many special manifestations of the vices; for vices vary, and there are countless phases of them, nor can all their various kinds be classified.
The method of maintaining righteousness is simple; the method of maintaining wickedness is complicated, and has infinite opportunity to swerve.
And the same holds true of character; if you follow nature, character is easy to manage, free, and with very slight shades of difference; but the sort of person I have mentioned possesses badly warped character, out of harmony with all things, including himself.

The chief cause, however, of this disease seems to me to be a squeamish revolt from the normal existence.
Just as such persons mark themselves off from others in their dress, or in the elaborate arrangement of their dinners, or in the elegance of their carriages; even so they desire to make themselves peculiar by their way of dividing up the hours of their day.
They are unwilling to be wicked in the conventional way, because notoriety is the reward of their sort of wickedness.
Notoriety is what all such men seek -- men who are, so to speak, *living backwards*.

For this reason, Lucilius, let us keep to the way which Nature has mapped out for us, and let us not swerve therefrom.
If we follow Nature, all is easy and unobstructed; but if we combat Nature, our life differs not a whit from that of men who row against the current.
Farewell.

[^122-1]: Vergil, *Georg.* i. 250 f.

[^122-2]: Cato, Frag. p. 110 Jordan.

[^122-3]: *i.e.*, owls, of ill omen.

[^122-4]: In connexion with the *Parentalia*, Feb. 13-21, and at other anniversary observations, the ceremonies were held in the daytime.

[^122-5]: A vice which Seneca especially abhors; *cf.* *Ep.* xv. 3 *multum potionis altius ieiunio iturae*.

[^122-6]: By wearing silk gowns of transparent material.

[^122-7]: Not literally translated. For the same thought see *Ep.* xlvii. 7, etc.
  [Wikisource: The Latin which Gummere refused to translate literally is "Numquam vir erit, ut diu virum pati possit? Et cum illum contumeliae sexus eripuisse debuerat, non ne aetas quidem eripiet?" or roughly: "Will he never become a man, so that he can continue to be screwed by men? And though his sex ought to spare him this insult, won't even his age spare him?"]

[^122-8]: The symbols of a Roman funeral. For the same practice, purposely performed, see *Ep.* xii. 8 (and the note of W. C. Summers).

[^122-9]: Called by Tacitus, *Ann.* iv. 34, a *Seiani cliens*.

[^122-10]: Baehrens, *Frag. Poet. Rom.* p. 355.

[^122-11]: *i.e.*, Procne, in the well-known nightingale myth.

[^122-12]: Son of the P. Vinicius ridiculed in *Ep.* xl. 9. He was husband of Julia, youngest daughter of Germanicus, and was poisoned by Messalina.

[^122-13]: *i.e.*, is punishing his slaves for errors in the day's work.

[^122-14]: *i.e.*, balancing the custom of the ordinary Roman, whose dinner never continued beyond nightfall.

[^122-15]: "'A liver by candle-light,' with a play on the word λίχνος, 'luxurious'" (Summers).
