# On Facing the World with Confidence

I shall now tell you certain things to which you should pay attention in order to live more safely.
Do you however, -- such is my judgment, -- hearken to my precepts just as if I were counselling you to keep safe your health in your country-place at Ardea.

Reflect on the things which goad man into destroying man: you will find that they are hope, envy, hatred, fear, and contempt.

Now, of all these, contempt is the least harmful, so much so that many have skulked behind it as a sort of cure.
When a man despises you, he works you injury, to be sure, but he passes on; and no one persistently or of set purpose does hurt to a person whom he despises.
Even in battle, prostrate soldiers are neglected: men fight with those who stand their ground.

And you can avoid the envious hopes of the wicked so long as you have nothing which can stir the evil desires of others, and so long as you possess nothing remarkable.
For people crave even little things, if these catch the attention or are of rare occurrence.

You will escape envy if you do not force yourself upon the public view, if you do not boast your possessions, if you understand how to enjoy things privately.
Hatred comes either from running foul of others: and this can be avoided by never provoking anyone; or else it is uncalled for: and common-sense[^105-1] will keep you safe from it.
Yet it has been dangerous to many; some people have been hated without having had an enemy.

As to not being feared, a moderate fortune and an easy disposition will guarantee you that; men should know that you are the sort of person who can be offended without danger; and your reconciliation should be easy and sure.
Moreover, it is as troublesome to be feared at home as abroad; it is as bad to be feared by a slave as by a gentleman.
For every one has strength enough to do you some harm.
Besides, he who is feared, fears also; no one has been able to arouse terror and live in peace of mind.

Contempt remains to be discussed.
He who has made this quality an adjunct of his own personality, who is despised because he wishes to be despised and not because he *must* be despised, has the measure of contempt under his control.
Any inconveniences in this respect can be dispelled by honourable occupations and by friendships with men who have influence with an influential person; with these men it will profit you to engage but not to entangle yourself, lest the cure may cost you more than the risk.

Nothing, however, will help you so much as keeping still -- talking very little with others, and as much as may be with yourself.
For there is a sort of charm about conversation, something very subtle and coaxing, which, like intoxication or love, draws secrets from us.
No man will keep to himself what he hears.
No one will tell another only as much as he has heard.
And he who tells tales will tell names, too.
Everyone has someone to whom he entrusts exactly what has been entrusted to him.
Though he checks his own garrulity, and is content with one hearer, he will bring about him a nation, if that which was a secret shortly before becomes common talk.

The most important contribution to peace of mind is never to do wrong.
Those who lack self-control lead disturbed and tumultuous lives; their crimes are balanced by their fears, and they are never at ease.
For they tremble after the deed, and they are embarrassed; their consciences do not allow them to busy themselves with other matters, and continually compel them to give an answer.
Whoever expects punishment, receives it, but whoever deserves it, expects it.

Where there is an evil conscience something may bring safety, but nothing can bring ease; for a man imagines that, even if he is not under arrest, he may soon be arrested.
His sleep is troubled; when he speaks of another man's crime, he reflects upon his own, which seems to him not sufficiently blotted out, not sufficiently hidden from view.
A wrongdoer sometimes has the luck to escape notice but never the assurance thereof.
Farewell.

[^105-1]: *i.e.*, tact.