# On Good Company

We are deceived by those who would have us believe that a multitude of affairs blocks their pursuit of liberal studies; they make a pretence of their engagements, and multiply them, when their engagements are merely with themselves.
As for me, Lucilius, my time is free; it is indeed free, and wherever I am, I am master of myself.
For I do not surrender myself to my affairs, but loan myself to them, and I do not hunt out excuses for wasting my time.
And wherever I am situated, I carry on my own meditations and ponder in my mind some wholesome thought.

When I give myself to my friends, I do not withdraw from my own company, nor do I linger with those who are associated with me through some special occasion or some case which arises from my official position.
But I spend my time in the company of all the best; no matter in what lands they may have lived, or in what age, I let my thoughts fly to them.

Demetrius,[^62-1] for instance, the best of men, I take about with me, and, leaving the wearers of purple and fine linen, I talk with him, half-naked as he is, and hold him in high esteem.
Why should I not hold him in high esteem?
I have found that he lacks nothing.
It is in the power of any man to despise all things, but of no man to possess all things.
The shortest cut to riches is to despise riches.
Our friend Demetrius, however, lives not merely as if he has learned to despise all things, but as if he has handed them over for others to possess.[^62-2]
Farewell.

[^62-1]: Demetrius of Sunium, the Cynic philosopher, who taught in Rome in the reign of Caligula and was banished by Nero.

[^62-2]: *i.e.*, he has achieved the Stoic ideal of independence of all external control; he is a king and has all things to bestow upon others, but needs nothing for himself.
