# On Harmful Prayers

I file a complaint, I enter a suit, I am angry.
Do you still desire what your nurse, your guardian, or your mother, have prayed for in your behalf?
Do you not yet understand what evil they prayed for?
Alas, how hostile to us are the wishes of our own folk!
And they are all the more hostile in proportion as they are more completely fulfilled.
It is no surprise to me, at my age, that nothing but evil attends us from our early youth; for we have grown up amid the curses invoked by our parents.
And may the gods give ear to our cry also, uttered in our own behalf, -- one which asks no favours!

How long shall we go on making demands upon the gods, as if we were still unable to support ourselves?
How long shall we continue to fill with grain the market-places of our great cities?
How long must the people gather it in for us?
How long shall many ships convey the requisites for a single meal, bringing them from no single sea?
The bull is filled when he feeds over a few acres; and one forest is large enough for a herd of elephants.
Man, however, draws sustenance both from the earth and from the sea.

What, then?
Did nature give us bellies so insatiable, when she gave us these puny bodies, that we should outdo the hugest and most voracious animals in greed?
Not at all.
How small is the amount which will satisfy nature?
A very little will send her away contented.
It is not the natural hunger of our bellies that costs us dear, but our solicitous cravings.

Therefore those who, as Sallust[^60-1] puts it, "hearken to their bellies," should be numbered among the animals, and not among men; and certain men, indeed, should be numbered, not even among the animals, but among the dead.
He really lives who is made use of by many; he really lives who makes use of himself.
Those men, however, who creep into a hole and grow torpid[^60-2] are no better off in their homes than if they were in their tombs.
Right there on the marble lintel of the house of such a man you may inscribe his name,[^60-3] for he has died before he is dead.
Farewell.

[^60-1]: *Catiline*, i. 1.

[^60-2]: *i.e.*, like animals.

[^60-3]: *i.e.*, you may put an epitaph upon his dwelling as if it were a tomb.
