# On Liberal and Vocational Studies

You have been wishing to know my views with regard to liberal studies.[^88-1]
My answer is this: I respect no study, and deem no study good, which results in money-making.
Such studies are profit-bringing occupations, useful only in so far as they give the mind a preparation and do not engage it permanently.
One should linger upon them only so long as the mind can occupy itself with nothing greater; they are our apprenticeship, not our real work.

Hence you see why "liberal studies" are so called; it is because they are studies worthy of a free-born gentleman.
But there is only one really liberal study, -- that which gives a man his liberty.
It is the study of wisdom, and that is lofty, brave, and great-souled.
All other studies are puny and puerile.
You surely do not believe that there is good in any of the subjects whose teachers are, as you see, men of the most ignoble and base stamp?
We ought not to be learning such things; we should have done with learning them.

Certain persons have made up their minds that the point at issue with regard to the liberal studies is whether they make men good; but they do not even profess or aim at a knowledge of this particular subject.

The scholar[^88-2] busies himself with investigations into language, and if it be his desire to go farther afield, he works on history, or, if he would extend his range to the farthest limits, on poetry.
But which of these paves the way to virtue?
Pronouncing syllables, investigating words, memorizing plays, or making rules for the scansion of poetry, -- what is there in all this that rids one of fear, roots out desire, or bridles the passions?

The question is: do such men teach virtue, or not?
If they do not teach it, then neither do they transmit it.
If they do teach it, they are philosophers.
Would you like to know how it happens that they have not taken the chair for the purpose of teaching virtue?
See how unlike their subjects are; and yet their subjects would resemble each other if they taught the same thing.[^88-3]

It may be, perhaps, that they make you believe that Homer was a philosopher,[^88-4] although they disprove this by the very arguments through which they seek to prove it.
For sometimes they make of him a Stoic, who approves nothing but virtue, avoids pleasures, and refuses to relinquish honour even at the price of immortality; sometimes they make him an Epicurean, praising the condition of a state in repose, which passes its days in feasting and song; sometimes a Peripatetic, classifying goodness in three ways;[^88-5] sometimes an Academic, holding that all things are uncertain.
It is clear, however, that no one of these doctrines is to be fathered upon Homer, just because they are all there; for they are irreconcilable with one another.
We may admit to these men, indeed, that Homer was a philosopher; yet surely he became a wise man before he had any knowledge of poetry.
So let us learn the particular things that made Homer wise.

It is no more to the point, of course, for me to investigate whether Homer or Hesiod was the older poet, than to know why Hecuba, although younger than Helen,[^88-6] showed her years so lamentably.
What, in your opinion, I say, would be the point in trying to determine the respective ages of Achilles and Patroclus?

Do you raise the question, "Through what regions did Ulysses stray?" instead of trying to prevent ourselves from going astray at all times?
We have no leisure to hear lectures on the question whether he was sea-tost between Italy and Sicily, or outside our known world (indeed, so long a wandering could not possibly have taken place within its narrow bounds); we ourselves encounter storms of the spirit, which toss us daily, and our depravity drives us into all the ills which troubled Ulysses.
For us there is never lacking the beauty to tempt our eyes, or the enemy to assail us; on this side are savage monsters that delight in human blood, on that side the treacherous allurements of the ear, and yonder is shipwreck and all the varied category of misfortunes.[^88-7]
Show me rather, by the example of Ulysses, how I am to love my country, my wife, my father, and how, even after suffering shipwreck, I am to sail toward these ends, honourable as they are.

Why try to discover whether Penelope was a pattern of purity,[^88-8] or whether she had the laugh on her contemporaries?
Or whether she suspected that the man in her presence was Ulysses, before she knew it was he?
Teach me rather what purity is, and how great a good we have in it, and whether it is situated in the body or in the soul.

Now I will transfer my attention to the musician.
You, sir, are teaching me how the treble and the bass[^88-9] are in accord with one another, and how, though the strings produce different notes, the result is a harmony; rather bring my soul into harmony with itself, and let not my purposes be out of tune.
You are showing me what the doleful keys[^88-10] are; show me rather how, in the midst of adversity, I may keep from uttering a doleful note.

The mathematician teaches me how to lay out the dimensions of my estates; but I should rather be taught how to lay out what is enough for a man to own.
He teaches me to count, and adapts my fingers to avarice; but I should prefer him to teach me that there is no point in such calculations, and that one is none the happier for tiring out the book-keepers with his possessions -- or rather, how useless property is to any man who would find it the greatest misfortune if he should be required to reckon out, by his own wits, the amount of his holdings.

What good is there for me in knowing how to parcel out a piece of land, if I know not how to share it with my brother?
What good is there in working out to a nicety the dimensions of an acre, and in detecting the error if a piece has so much as escaped my measuring-rod, if I am embittered when an ill-tempered neighbour merely scrapes off a bit of my land?
The mathematician teaches me how I may lose none of my boundaries; I, however, seek to learn how to lose them all with a light heart.

"But," comes the reply, "I am being driven from the farm which my father and grandfather owned!"
Well?
Who owned the land before your grandfather?
Can you explain what people (I will not say what person) held it originally?
You did not enter upon it as a master, but merely as a tenant.
And whose tenant are you?
If your claim is successful, you are tenant of the heir.
The lawyers say that public property cannot be acquired privately by possession;[^88-11] what you hold and call your own is public property -- indeed, it belongs to mankind at large.

O what marvellous skill!
You know how to measure the circle; you find the square of any shape which is set before you; you compute the distances between the stars; there is nothing which does not come within the scope of your calculations.
But if you are a real master of your profession, measure me the mind of man!
Tell me how great it is, or how puny!
You know what a straight line is; but how does it benefit you if you do not know what is straight in this life of ours?

I come next to the person who boasts his knowledge of the heavenly bodies, who knows

> Whither the chilling star of Saturn hides,  
And through what orbit Mercury doth stray.[^88-12]

Of what benefit will it be to know this?
That I shall be disturbed because Saturn and Mars are in opposition, or when Mercury sets at eventide in plain view of Saturn, rather than learn that those stars, wherever they are, are propitious,[^88-13] and that they are not subject to change?

They are driven along by an unending round of destiny, on a course from which they cannot swerve.
They return at stated seasons; they either set in motion, or mark the intervals of the whole world's work.
But if they are responsible for whatever happens, how will it help you to know the secrets of the immutable?
Or if they merely give indications, what good is there in foreseeing what you cannot escape?
Whether you know these things or not, they will take place.

> Behold the fleeting sun,  
The stars that follow in his train, and thou  
Shalt never find the morrow play thee false,  
Or be misled by nights without a cloud.[^88-14]

It has, however, been sufficiently and fully ordained that I shall be safe from anything that may mislead me.

"What," you say, "does the 'morrow never play me false'?
Whatever happens without my knowledge plays me false."
I, for my part, do not know what is to be, but I do know what may come to be.
I shall have no misgivings in this matter; I await the future in its entirety; and if there is any abatement in its severity, I make the most of it.
If the morrow treats me kindly, it is a sort of deception; but it does not deceive me even at that.
For just as I know that all things can happen, so I know, too, that they will not happen in every case.
I am ready for favourable events in every case, but I am prepared for evil.

In this discussion you must bear with me if I do not follow the regular course.
For I do not consent to admit painting into the list of liberal arts, any more than sculpture, marble-working, and other helps toward luxury.
I also debar from the liberal studies wrestling and all knowledge that is compounded of oil and mud;[^88-15] otherwise, I should be compelled to admit perfumers also, and cooks, and all others who lend their wits to the service of our pleasures.

For what "liberal" element is there in these ravenous takers of emetics, whose bodies are fed to fatness while their minds are thin and dull?[^88-16]
Or do we really believe that the training which they give is "liberal" for the young men of Rome, who used to be taught by our ancestors to stand straight and hurl a spear, to wield a pike, to guide a horse, and to handle weapons?
Our ancestors used to teach their children nothing that could be learned while lying down.
But neither the new system nor the old teaches or nourishes virtue.
For what good does it do us to guide a horse and control his speed with the curb, and then find that our own passions, utterly uncurbed, bolt with us?
Or to beat many opponents in wrestling or boxing, and then to find that we ourselves are beaten by anger?

"What then," you say, "do the liberal studies contribute nothing to our welfare?"
Very much in other respects, but nothing at all as regards virtue.
For even these arts of which I have spoken, though admittedly of a low grade -- depending as they do upon handiwork -- contribute greatly toward the equipment of life, but nevertheless have nothing to do with virtue.
And if you inquire, "Why, then, do we educate our children in the liberal studies?"[^88-17] it is not because they can bestow virtue, but because they prepare the soul for the reception of virtue.
Just as that "primary course,"[^88-18] as the ancients called it, in grammar, which gave boys their elementary training, does not teach them the liberal arts, but prepares the ground for their early acquisition of these arts, so the liberal arts do not conduct the soul all the way to virtue, but merely set it going in that direction.

Posidonius[^88-19] divides the arts into four classes: first we have those which are common and low, then those which serve for amusement, then those which refer to the education of boys, and, finally, the liberal arts.
The common sort belong to workmen and are mere hand-work; they are concerned with equipping life; there is in them no pretence to beauty or honour.

The arts of amusement are those which aim to please the eye and the ear.
To this class you may assign the stage-machinists, who invent scaffolding that goes aloft of its own accord, or floors that rise silently into the air, and many other surprising devices, as when objects that fit together then fall apart, or objects which are separate then join together automatically, or objects which stand erect then gradually collapse.
The eye of the inexperienced is struck with amazement by these things; for such persons marvel at everything that takes place without warning, because they do not know the causes.

The arts which belong to the education of boys, and are somewhat similar to the liberal arts, are those which the Greeks call the "cycle of studies,"[^88-20] but which we Romans call the "liberal."
However, those alone are really liberal -- or rather, to give them a truer name, "free" -- whose concern is virtue.

"But," one will say, "just as there is a part of philosophy which has to do with nature, and a part which has to do with ethics, and a part which has to do with reasoning, so this group of liberal arts also claims for itself a place in philosophy.
When one approaches questions that deal with nature, a decision is reached by means of a word from the mathematician.
Therefore mathematics is a department of that branch which it aids."[^88-21]

But many things aid us and yet are not parts of ourselves.
Nay, if they were, they would not aid us.
Food is an aid to the body, but is not a part of it.
We get some help from the service which mathematics renders; and mathematics is as indispensable to philosophy as the carpenter is to the mathematician.
But carpentering is not a part of mathematics, nor is mathematics a part of philosophy.

Moreover, each has its own limits; for the wise man investigates and learns the causes of natural phenomena, while the mathematician follows up and computes their numbers and their measurements.[^88-22]
The wise man knows the laws by which the heavenly bodies persist, what powers belong to them, and what attributes; the astronomer merely notes their comings and goings, the rules which govern their settings and their risings, and the occasional periods during which they seem to stand still, although as a matter of fact no heavenly body can stand still.

The wise man will know what causes the reflection in a mirror; but the mathematician can merely tell you how far the body should be from the reflection, and what shape of mirror will produce a given reflection.[^88-23]
The philosopher will demonstrate that the sun is a large body, while the astronomer will compute just how large, progressing in knowledge by his method of trial and experiment; but in order to progress, he must summon to his aid certain principles.
No art, however, is sufficient unto itself, if the foundation upon which it rests depends upon mere favour.

Now philosophy asks no favours from any other source; it builds everything on its own soil; but the science of numbers is, so to speak, a structure built on another man's land -- it builds on alien soil.[^88-24]
It accepts first principles, and by their favour arrives at further conclusions.
If it could march unassisted to the truth, if it were able to understand the nature of the universe, I should say that it would offer much assistance to our minds; for the mind grows by contact with things heavenly, and draws into itself something from on high.
There is but one thing that brings the soul to perfection -- the unalterable knowledge of good and evil.
But there is no other art[^88-25] which investigates good and evil.

I should like to pass in review the several virtues.

Bravery is a scorner of things which inspire fear; it looks down upon, challenges, and crushes the powers of terror and all that would drive our freedom under the yoke.
But do "liberal studies"[^88-26] strengthen this virtue?
Loyalty is the holiest good in the human heart; it is forced into betrayal by no constraint, and it is bribed by no rewards.
Loyalty cries: "Burn me, slay me, kill me!
I shall not betray my trust; and the more urgently torture shall seek to find my secret, the deeper in my heart will I bury it!"
Can the "liberal arts" produce such a spirit within us?
Temperance controls our desires; some it hates and routs, others it regulates and restores to a healthy measure, nor does it ever approach our desires for their own sake.
Temperance knows that the best measure of the appetites is not what you want to take, but what you ought to take.

Kindliness forbids you to be over-bearing towards your associates, and it forbids you to be grasping.
In words and in deeds and in feelings it shows itself gentle and courteous to all men.
It counts no evil as another's solely.
And the reason why it loves its own good is chiefly because it will some day be the good of another.
Do "liberal studies" teach a man such character as this?
No; no more than they teach simplicity, moderation and self-restraint, thrift and economy, and that kindliness which spares a neighbour's life as if it were one's own and knows that it is not for man to make wasteful use of his fellow-man.

"But," one says, "since you declare that virtue cannot be attained without the 'liberal studies,' how is it that you deny that they offer any assistance to virtue?"[^88-27]
Because you cannot attain virtue without food, either; and yet food has nothing to do with virtue.
Wood does not offer assistance to a ship, although a ship cannot be built except of wood.
There is no reason, I say, why you should think that anything is made by the assistance of that without which it cannot be made.

We might even make the statement that it is possible to attain wisdom without the "liberal studies"; for although virtue is a thing that must be learned, yet it is not learned by means of these studies.

What reason have I, however, for supposing that one who is ignorant of letters will never be a wise man, since wisdom is not to be found in letters?
Wisdom communicates facts[^88-28] and not words; and it may be true that the memory is more to be depended upon when it has no support outside itself.

Wisdom is a large and spacious thing.
It needs plenty of free room.
One must learn about things divine and human, the past and the future, the ephemeral and the eternal; and one must learn about Time.[^88-29]
See how many questions arise concerning time alone: in the first place, whether it is anything in and by itself; in the second place, whether anything exists prior to time and without time; and again, did time begin along with the universe, or, because there was something even before the universe began, did time also exist then?

There are countless questions concerning the soul alone: whence it comes, what is its nature, when it begins to exist, and how long it exists; whether it passes from one place to another and changes its habitation, being transferred successively from one animal shape to another, or whether it is a slave but once, roaming the universe after it is set free; whether it is corporeal or not; what will become of it when it ceases to use us as its medium; how it will employ its freedom when it has escaped from this present prison; whether it will forget all its past, and at that moment begin to know itself when, released from the body, it has withdrawn to the skies.

Thus, whatever phase of things human and divine you have apprehended, you will be wearied by the vast number of things to be answered and things to be learned.
And in order that these manifold and mighty subjects may have free entertainment in your soul, you must remove therefrom all superfluous things.
Virtue will not surrender herself to these narrow bounds of ours; a great subject needs wide space in which to move.
Let all other things be driven out, and let the breast be emptied to receive virtue.

"But it is a pleasure to be acquainted with many arts."
Therefore let us keep only as much of them as is essential.
Do you regard that man as blameworthy who puts superfluous things on the same footing with useful things, and in his house makes a lavish display of costly objects, but do not deem him blameworthy who has allowed himself to become engrossed with the useless furniture of learning?
This desire to know more than is sufficient is a sort of intemperance.

Why?
Because this unseemly pursuit of the liberal arts makes men troublesome, wordy, tactless, self-satisfied bores, who fail to learn the essentials just because they have learned the non-essentials.
Didymus the scholar wrote four thousand books.
I should feel pity for him if he had only read the same number of superfluous volumes.
In these books he investigates Homer's birthplace,[^88-30] who was really the mother of Aeneas, whether Anacreon was more of a rake or more of a drunkard, whether Sappho was a bad lot,[^88-31] and other problems the answers to which, if found, were forthwith to be forgotten.
Come now, do not tell me that life is long!

Nay, when you come to consider our own countrymen also, I can show you many works which ought to be cut down with the axe.

It is at the cost of a vast outlay of time and of vast discomfort to the ears of others that we win such praise as this: "What a learned man you are!"
Let us be content with this recommendation, less citified though it be: "What a good man you are!"

Do I mean this?
Well, would you have me unroll the annals of the world's history and try to find out who first wrote poetry?
Or, in the absence of written records, shall I make an estimate of the number of years which lie between Orpheus and Homer?
Or shall I make a study of the absurd writings of Aristarchus, wherein he branded the text[^88-32] of other men's verses, and wear my life away upon syllables?
Shall I then wallow in the geometrician's dust?[^88-33]
Have I so far forgotten that useful saw "Save your time"?
Must I know these things?
And what may I choose not to know?

Apion, the scholar, who drew crowds to his lectures all over Greece in the days of Gaius Caesar and was acclaimed a Homerid[^88-34] by every state, used to maintain that Homer, when he had finished his two poems, the *Iliad* and the *Odyssey*, added a preliminary poem to his work, wherein he embraced the whole Trojan war.[^88-35]
The argument which Apion adduced to prove this statement was that Homer had purposely inserted in the opening line two letters which contained a key to the number of his books.

A man who wishes to know many things must know such things as these, and must take no thought of all the time which one loses by ill-health, public duties, private duties, daily duties, and sleep.
Apply the measure to the years of your life; they have no room for all these things.

I have been speaking so far of liberal studies; but think how much superfluous and unpractical matter the philosophers contain!
Of their own accord they also have descended to establishing nice divisions of syllables, to determining the true meaning of conjunctions and prepositions; they have been envious of the scholars, envious of the mathematicians.
They have taken over into their own art all the superfluities of these other arts; the result is that they know more about careful speaking than about careful living.

Let me tell you what evils are due to over-nice exactness, and what an enemy it is of truth!
Protagoras declares that one can take either side on any question and debate it with equal success -- even on this very question, whether every subject can be debated from either point of view.
Nausiphanes holds that in things which seem to exist, there is no difference between existence and non-existence.

Parmenides maintains that nothing exists of all this which seems to exist, except the universe alone.[^88-36]
Zeno of Elea removed all the difficulties by removing one; for he declares that nothing exists.
The Pyrrhonean, Megarian, Eretrian, and Academic schools are all engaged in practically the same task; they have introduced a new knowledge, non-knowledge.

You may sweep all these theories in with the superfluous troops of "liberal" studies; the one class of men give me a knowledge that will be of no use to me, the other class do away with any hope of attaining knowledge.
It is better, of course, to know useless things than to know nothing.
One set of philosophers offers no light by which I may direct my gaze toward the truth; the other digs out my very eyes and leaves me blind.
If I cleave to Protagoras, there is nothing in the scheme of nature that is not doubtful; if I hold with Nausiphanes, I am sure only of this -- that everything is unsure; if with Parmenides, there is nothing except the One;[^88-37] if with Zeno, there is not even the One.

What are we, then?
What becomes of all these things that surround us, support us, sustain us?
The whole universe is then a vain or deceptive shadow.
I cannot readily say whether I am more vexed at those who would have it that we know nothing, or with those who would not leave us even this privilege.
Farewell.

[^88-1]: The regular round of education, ἐγκύκλιος παιδεία, including grammar, music, geometry, arithmetic, astrology, and certain phases of rhetoric and dialectic, are in this letter contrasted with liberal studies -- those which have for their object the pursuit of virtue. Seneca is thus interpreting *studia liberalia* in a higher sense than his contemporaries would expect. Compare J. R. Lowell's definition of a university, "a place where nothing useful is taught."

[^88-2]: *Grammaticus* in classical Greek means "one who is familiar with the alphabet"; in the Alexandrian age a "student of literature"; in the Roman age the equivalent of *litteratus*. Seneca means here a "specialist in linguistic science."

[^88-3]: *i.e.*, philosophy (virtue).

[^88-4]: This theory was approved by Democritus, Hippias of Elis, and the allegorical interpreters; Xenophanes, Heraclitus, and Plato himself condemned Homer for his supposed unphilosophic fabrications.

[^88-5]: The *tria genera bonorum* of Cicero's *De Fin* v. 84. Cf. *ib.* 18, where the three proper objects of man's search are given as the desire for pleasure, the avoidance of pain, and the attainment of such natural goods as health, strength, and soundnesss of mind. The Stoics held that the good was absolute.

[^88-6]: Summers compares Lucian, *Gall.* 17. Seneca, however, does not take such gossip seriously.

[^88-7]: This sentence alludes to Calypso, Circe, the Cyclops, and the Sirens.

[^88-8]: Unfavourable comment by Lycophron, and by Cicero, *De Nat. Deor.* iii. 22 *(Mercurius) ex quo et Penelopa Pana natum ferunt*.

[^88-9]: With *acutae* and *graves* supply *voces*.

[^88-10]: Perhaps the equivalent of a "minor."

[^88-11]: *i.e.*, for a certain term of years; see R. W. Leage, *Roman Private Law*, pp. 133 ff. Compare also Lucretius iii. 971, and Horace, *Ep.* ii. 2. 159.

[^88-12]: Vergil, *Georg.* i. 336 f.

[^88-13]: Saturn and Mars were regarded as unlucky stars. Astrology, which dates back beyond 3000 B.C. in Babylonia, was developed by the Greeks of the Alexandrian age and got a foothold in Rome by the second century B.C., flourished greatly under Tiberius. Cf. Horace, *Od.* i. 11. 1 f.; Juv. iii. 42 f., and F. Cumont, *Astrology and Religion among the Greeks and Romans* (trans.), esp. pp. 68 ff. and 84 ff.

[^88-14]: Vergil, *Georg.* i. 424 ff.

[^88-15]: An allusion to the sand and oil of the wrestling-ring.

[^88-16]: *Cf.* *Ep.* xv. 3 *copia ciborum subtilitas inpeditur*.

[^88-17]: In a strict sense; not, as in § 2, as Seneca thinks that the term should really be defined -- the "liberal" study, *i.e.* the pursuit of wisdom.

[^88-18]: For the πρώτη ἀγωγή see Quintilian, ii. 1. 4.

[^88-19]: From what work of Posidonius Seneca is here quoting we do not know; it may perhaps be from the Προτρεπτικά, or *Exhortations*, indicating the training preliminary to philosophy.

[^88-20]: See note *a*, p. 348.

[^88-21]: *i.e.*, mathematics is a department of *philosophia naturalis*.

[^88-22]: This line of argument inversely resembles the criticism by Seneca of Posidonius in *Ep.* xc. -- that the inventions of early science cannot be properly termed a part of philosophy.

[^88-23]: See *N.Q.* i. 4 ff.

[^88-24]: According to Roman law, *superficies solo cedit*, "the building goes with the ground."

[^88-25]: Except philosophy.

[^88-26]: *i.e.*, in the more commonly accepted sense of the term.

[^88-27]: This usage is a not infrequent one in Latin; cf. Petronius, *Sat.* 42 *neminem nihil boni facere oportet*; *id. ib.* 58; Verg. *Ecl.* v. 25, etc. See Draeger, *Hist. Syn.* ii. 75, and Roby, ii. 2246 ff.

[^88-28]: *Cf.* *Epp.* xxxi. 6 and lxxxi. 29 *aestimare res, de quibus . . . cum rerum natura deliberandum est*.

[^88-29]: The ancient Stoics defined Time as "extension of the world's motion." The seasons were said to be "alive" because they depended on material conditions. But the Stoics really acknowledged Time to be immaterial. The same problem of corporeality was discussed with regard to the "good."

[^88-30]: Compare the schoolmaster of Juvenal (vii. 234 ff.), who must know: *"Nutricem Anchisae, nomen patriamque novercae. Anchemoli, dicat quot Acestes vixerit annis, etc.,"* and Friedländer's note.

[^88-31]: A tradition, probably begun by the Greek comic writers, and explained by Professor Smyth (*Greek Melic Poets*, pp. 227 f.) as due to the more independent position of women among the Aeolians.
  [Wikisource: Gummere has euphemistically translated Seneca here. The Latin is "in his an Sappho publica fuerit", and the feminine noun "publica" means "public woman", *i.e.* a courtesan or prostitute. So Gummere's translation "whether Sappho was a bad lot" is more accurately rendered as "whether Sappho was a prostitute."]

[^88-32]: Marking supposedly spurious lines by the *obelus*, and using other signs to indicate variations, repetitions, and interpolations. He paid special attention to Homer, Pindar, Hesiod, and the tragedians.

[^88-33]: The geometricians drew their figures in the dust or sand.

[^88-34]: Originally, rhapsodists who recited from Homer; in general, "interpreters and admirers -- in short, the whole 'spiritual kindred' -- of Homer" (D. B. Monro)

[^88-35]: An ancient explanation of the (now disproved) authorship by Homer of such poems as the *Cypria*, *Little Iliad*, *Sack of Troy*, etc.

[^88-36]: In other words, the unchangeable, perfect Being of the universe is contrasted with the mutable Non-Being of opinion and unreality.

[^88-37]: *i.e.*, the universe.
