# On Meeting Death Cheerfully

Let us cease to desire that which we have been desiring.
I, at least, am doing this: in my old age I have ceased to desire what I desired when a boy.
To this single end my days and my nights are passed; this is my task, this the object of my thoughts, -- to put an end to my chronic ills.
I am endeavouring to live every day as if it were a complete life.
I do not indeed snatch it up as if it were my last; I do regard it, however, as if it might even be my last.

The present letter is written to you with this in mind, -- as if death were about to call me away in the very act of writing.
I am ready to depart, and I shall enjoy life just because I am not over-anxious as to the future date of my departure.

Before I became old I tried to live well; now that I am old, I shall try to die well; but dying well means dying gladly.
See to it that you never do anything unwillingly.

That which is bound to be a necessity if you rebel, is not a necessity if you desire it.
This is what I mean: he who takes his orders gladly, escapes the bitterest part of slavery, -- doing what one does not want to do.
The man who does something under orders is not unhappy; he is unhappy who does something against his will.
Let us therefore so set our minds in order that we may desire whatever is demanded of us by circumstances, and above all that we may reflect upon our end without sadness.

We must make ready for death before we make ready for life.
Life is well enough furnished, but we are too greedy with regard to its furnishings; something always seems to us lacking, and will always seem lacking.
To have lived long enough depends neither upon our years nor upon our days, but upon our minds.
I have lived, my dear friend Lucilius, long enough.
I have had my fill;[^61-1] I await death.
Farewell.

[^61-1]: A reminiscence of Lucretius, iii. 938 f. *Cur non ut plenus vitae conviva recedis Aequo animoque capis securam, stulte, quietem?* *Cf.* also Horace, *Sat.* i. 1. 118 f. *vitae Cedat uti conviva satur*.
