# On Philosophers and Kings

[^73-1] It seems to me erroneous to believe that those who have loyally dedicated themselves to philosophy are stubborn and rebellious, scorners of magistrates or kings or of those who control the administration of public affairs.
For, on the contrary, no class of man is so popular with the philosopher as the ruler is; and rightly so, because rulers bestow upon no men a greater privilege than upon those who are allowed to enjoy peace and leisure.

Hence, those who are greatly profited, as regards their purpose of right living, by the security of the State, must needs cherish as a father the author of this good; much more so, at any rate, than those restless persons who are always in the public eye, who owe much to the ruler, but also expect much from him, and are never so generously loaded with favours that their cravings, which grow by being supplied, are thoroughly satisfied.
And yet he whose thoughts are of benefits to come has forgotten the benefits received; and there is no greater evil in covetousness than its ingratitude.

Besides, no man in public life thinks of the many whom he has outstripped; he thinks rather of those by whom he is outstripped.
And these men find it less pleasing to see many behind them than annoying to see anyone ahead of them.[^73-2]
That is the trouble with every sort of ambition; it does not look back.
Nor is it ambition alone that is fickle, but also every sort of craving, because it always begins where it ought to end.

But that other man, upright and pure, who has left the senate and the bar and all affairs of state, that he may retire to nobler affairs,[^73-3] cherishes those who have made it possible for him to do this in security; he is the only person who returns spontaneous thanks to them, the only person who owes them a great debt without their knowledge.
Just as a man honours and reveres his teachers, by whose aid he has found release from his early wanderings, so the sage honours these men, also, under whose guardianship he can put his good theories into practice.

But you answer: "Other men too are protected by a king's personal power."
Perfectly true.
But just as, out of a number of persons who have profited by the same stretch of calm weather, a man deems that his debt to Neptune is greater if his cargo during that voyage has been more extensive and valuable, and just as the vow is paid with more of a will by the merchant than by the passenger, and just as, from among the merchants themselves, heartier thanks are uttered by the dealer in spices, purple fabrics, and objects worth their weight in gold, than by him who has gathered cheap merchandise that will be nothing but ballast for his ship; similarly, the benefits of this peace, which extends to all, are more deeply appreciated by those who make good use of it.

For there are many of our toga-clad citizens to whom peace brings more trouble than war.
Or do those, think you, owe as much as we do for the peace they enjoy, who spend it in drunkenness, or in lust, or in other vices which it were worth even a war to interrupt?
No, not unless you think that the wise man is so unfair as to believe that as an individual he owes nothing in return for the advantages which he enjoys with all the rest.
I owe a great debt to the sun and to the moon; and yet they do not rise for me alone.
I am personally beholden to the seasons and to the god who controls them, although in no respect have they been apportioned for my benefit.

The foolish greed of mortals makes a distinction between possession and ownership,[^73-4] and believes that it has ownership in nothing in which the general public has a share.
But our philosopher considers nothing more truly his own than that which he shares in partnership with all mankind.
For these things would not be common property, as indeed they are, unless every individual had his quota; even a joint interest based upon the slightest share makes one a partner.

Again, the great and true goods are not divided in such a manner that each has but a slight interest; they belong in their entirety to each individual.
At a distribution of grain men receive only the amount that has been promised to each person; the banquet and the meat-dole,[^73-5] or all else that a man can carry away with him, are divided into parts.
These goods, however, are indivisible, -- I mean peace and liberty, -- and they belong in their entirety to all men just as much as they belong to each individual.

Therefore the philosopher thinks of the person who makes it possible for him to use and enjoy these things, of the person who exempts him when the state's dire need summons to arms, to sentry duty, to the defence of the walls, and to the manifold exactions of war; and he gives thanks to the helmsman of his state.
This is what philosophy teaches most of all, -- honourably to avow the debt of benefits received, and honourably to pay them; sometimes, however, the acknowledgment itself constitutes payment.

Our philosopher will therefore acknowledge that he owes a large debt to the ruler who makes it possible, by his management and foresight, for him to enjoy rich leisure, control of his own time, and a tranquillity uninterrupted by public employments.

> Shepherd! a god this leisure gave to me,  
For he shall be my god eternally.[^73-6]

And if even such leisure as that of our poet owes a great debt to its author, though its greatest boon is this:

> As thou canst see,  
He let me turn my cattle out to feed,  
And play what fancy pleased on rustic reed;[^73-7]

<p style="text-indent: 0">how highly are we to value this leisure of the philosopher, which is spent among the gods, and makes us gods?</p>

Yes, that is what I mean, Lucilius; and I invite you to heaven by a short cut.

Sextius used to say that Jupiter had no more power than the good man.
Of course, Jupiter has more gifts which he can offer to mankind; but when you are choosing between two good men, the richer is not necessarily the better, any more than, in the case of two pilots of equal skill in managing the tiller, you would call him the better whose ship is larger and more imposing.

In what respect is Jupiter superior to our good man?
His goodness lasts longer; but the wise man does not set a lower value upon himself, just because his virtues are limited by a briefer span.
Or take two wise men; he who has died at a greater age is not happier than he whose virtue has been limited to fewer years: similarly, a god has no advantage over a wise man in point of happiness,[^73-8] even though he has such an advantage in point of years.
That virtue is not greater which lasts longer.

Jupiter possesses all things, but he has surely given over the possession of them to others; the only use of them which belongs to him is this: he is the cause of their use to all men.
The wise man surveys and scorns all the possessions of others as calmly as does Jupiter, and regards himself with the greater esteem because, while Jupiter cannot make use of them, he, the wise man, does not wish to do so.

Let us therefore believe Sextius when he shows us the path of perfect beauty, and cries: "This is 'the way to the stars';[^73-9] this is the way, by observing thrift, self-restraint, and courage!"

The gods are not disdainful or envious; they open the door to you; they lend a hand as you climb.

Do you marvel that man goes to the gods?
God comes to men; nay, he comes nearer, -- he comes into men.[^73-10]
No mind that has not God, is good.
Divine seeds are scattered throughout our mortal bodies; if a good husbandman receives them, they spring up in the likeness of their source and of a parity with those from which they came.
If, however, the husbandman be bad, like a barren or marshy soil, he kills the seeds, and causes tares to grow up instead of wheat.
Farewell.

[^73-1]: This letter is especially interesting because of its autobiographical hints, and its relation to Seneca's own efforts to be rid of court life and seek the leisure of the sage. See the Introduction to Vol. I. pp. viii f.

[^73-2]: *Cf.* Horace, *Sat.* i. 1. 115f. "Instat equis auriga suos vincentibus, illum. Praeteritum temnens extremos inter euntem.*

[^73-3]: For an interesting account of philosophy and its relation to Roman history see E. V. Arnold, *Roman Stoicism*, chap. xvi. This subject is discussed fully by Cicero, *De Off.* i. 71 f., and by Seneca, *Ep.* xc.

[^73-4]: For this figure *cf.* *Ep.* lxxii. 7 and note; see also the similar language of lxxxviii. 12 *hoc, quod tenes, quod tuum dicis, publicum est et quidem generis humani*.

[^73-5]: During certain festivals, either cooked or raw meat was distributed among the people.

[^73-6]: Vergil, *Eclogue*, i. 6 f. Vergil owes a debt to the Emperor, and regards him as a "god" because of the bestowal of earthly happiness; how much greater is the debt of the philosopher, who has the opportunity to study heavenly things!

[^73-7]: Vergil, *Eclogue*, i. 9 f.

[^73-8]: In the Christian religion, God is everything; among the Stoics, the wise man is equal to the gods. *Cf.*, for example, *Ep.* xli. 4.

[^73-9]: Vergil, *Aeneid*, ix. 641.

[^73-10]: *Cf.* *Ep.* xli. §§ 1 f. *prope est a te deus, tecum est, intus est*.
