# On Quiet Conversation

You are right when you urge that we increase our mutual traffic in letters.
But the greatest benefit is to be derived from conversation, because it creeps by degrees into the soul.
Lectures prepared beforehand and spouted in the presence of a throng have in them more noise but less intimacy.
Philosophy is good advice; and no one can give advice at the top of his lungs.
Of course we must sometimes also make use of these harangues, if I may so call them, when a doubting member needs to be spurred on; but when the aim is to make a man learn, and not merely to make him wish to learn, we must have recourse to the low-toned words of conversation.
They enter more easily, and stick in the memory; for we do not need many words, but, rather, effective words.

Words should be scattered like seed; no matter how small the seed may be, if it has once found favourable ground, it unfolds its strength and from an insignificant thing spreads to its greatest growth.
Reason grows in the same way; it is not large to the outward view, but increases as it does its work.
Few words are spoken; but if the mind has truly caught them, they come into their strength and spring up.
Yes, precepts and seeds have the same quality; they produce much, and yet they are slight things.
Only, as I said, let a favourable mind receive and assimilate them.
Then of itself the mind also will produce bounteously in its turn, giving back more than it has received.
Farewell.
